In [1]:
#import Required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Load the dataset
df=pd.read_csv(r"C:\diabetes\Purchase_new.csv")

In [4]:
df.head(10)

  Holiday Discount Free Delivery Purchase
0      No      Yes           Yes      Yes
1      No      Yes           Yes      Yes
2      No       No            No       No
3     yes      Yes           Yes      Yes
4     yes      Yes           Yes      Yes
5     yes       No            No       No
6     yes      Yes            No      Yes
7      No      Yes           Yes      Yes
8     yes      Yes           Yes      Yes
9     yes      Yes           Yes      Yes

In [10]:
x = df.drop(['Purchase','Holiday','Free Delivery'],axis=1)
y = df['Purchase']

In [44]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le=LabelEncoder()
df["Purchase"]=le.fit_transform(df["Purchase"])

In [23]:
df["Free Delivery"]=le.fit_transform(df["Free Delivery"])

In [25]:
df["Holiday"]=le.fit_transform(df["Holiday"])

In [27]:
df["Discount"]=le.fit_transform(df["Discount"])

In [29]:
df.head(10)

   Holiday  Discount  Free Delivery  Purchase
0        0         1              1         1
1        0         1              1         1
2        0         0              0         0
3        1         1              1         1
4        1         1              1         1
5        1         0              0         0
6        1         1              0         1
7        0         1              1         1
8        1         1              1         1
9        1         1              1         1

In [31]:
df.corr()

                Holiday  Discount  Free Delivery  Purchase
Holiday        1.000000 -0.244558      -0.092675 -0.034586
Discount      -0.244558  1.000000       0.445823  0.530330
Free Delivery -0.092675  0.445823       1.000000  0.512272
Purchase      -0.034586  0.530330       0.512272  1.000000

In [39]:
#divide the data into x and y variable
x=df.drop(columns=['Purchase'],axis=True)
y=df['Purchase']

In [45]:
x=df.drop(['Purchase','Holiday'],axis=1)
y=df['Purchase']

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [49]:
#Initialize the decision tree classifier

from sklearn.tree import DecisionTreeClassifier 
dt=DecisionTreeClassifier()

In [ ]:
# train the model
model=dt.fit(x_train,y_train)

In [ ]:
# predict on test set
y_pred=model.predict(x_test)

In [59]:
# calculation accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [56]:
for column in df.columns:
    df[column]=le.fit_transform(df[column])

In [62]:
print(accuracy)

1.0

In [67]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
dt=DecisionTreeClassifier()

In [68]:
model=dt.fit(x_train,y_train)
model1=lr.fit(x_train,y_train)